### ISSUE TITLE
Ghid instalare manuală pentru MacOS

### ISSUE THREAD

**Issue by yoyosan** [gov-ithub/StopCozi-devops#2]
Scrie un ghid pentru instalarea manuală a serviciilor necesare pentru a rula aplicaţia pe MacOS.

Ghidul poate fi accesat [aici](https://github.com/gov-ithub/StopCozi-devops/wiki/Instalare-manual%C4%83#macos).

**Comment by AndreiDuma** [comment]
Eu nu am Mac și nici nu mă pricep. @vladiulianbogdan, te ocupi tu?

**Comment by vladiulianbogdan** [comment]
Sure.
